### ISSUE TITLE
replying in comments sometimes adds the reply at the top of the comment thread

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#83] opened 2023-10-10 17:02 UTC
but sometimes if you refresh the page it fixes itself, so might just be a transient front-end thing

**Comment by alasdairwilson** [comment] 2024-10-16 19:35
This seems to be mostly resolved and was never reproducibly reliably anyway so I am closing for now.

**Closed by alasdairwilson** 2024-10-16 19:35 UTC
Labels: bug
